import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import "./globals.css";


const geistSans = Open_Sans({
	variable: "--font-geist-sans",
	subsets: ["latin", "cyrillic"]
});

export const metadata: Metadata = {
	title: "Pizza App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistSans.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
